"""Generates the SANITIZED sample weekly report published on GitHub Pages
(docs/sample/weekly_report_sample.html).

  py -3.10 -m scripts.make_sample_report

Sanitization is the hard requirement (2026-09-03, owner): no Sleeper usernames, no real
team names, no league IDs -- nothing traceable to the actual league. Real NFL player
names STAY (public data; an anonymized tier chart would be meaningless). The approach is
a FULL run against sanitized config rather than post-processing, because ~10 chart PNGs
carry team names baked into titles, axes and filenames -- regeneration is the only fix,
and it keeps every artifact consistent:

  * config.TEAM_NAME_MAP's VALUES are mutated in place to fictional names, so the whole
    pipeline (rosters, standings, charts, filenames) runs under fiction end-to-end;
  * MANAGER_PROFILES is re-keyed the same way, so simulated behavior is IDENTICAL to a
    real run rather than falling back to anonymous defaults;
  * the run executes in an isolated scratch directory (the backtest's chdir pattern), so
    it fetches live NFL data but can never read the real decision log; the decision-log
    section instead renders ILLUSTRATIVE fictional rows, labeled as such in the page.

The final artifact is LEAK-CHECKED before writing: every real team name, every Sleeper
username, and both league IDs must be absent or this script refuses to publish.
"""
import datetime as _dt
import json
import os
import re
import shutil
import sys
import tempfile

# The fictional league. Clearly invented; the operator's team is the Quantum Ferrets.
FICTIONAL = {
    "Legion of Coom": "Quantum Ferrets",
    "Canton Killers": "Crimson Marmots",
    "Wine Drinkers": "Iron Wombats",
    "Femboy Cats": "Neon Walruses",
    "Clankers": "Turbo Llamas",
    "The Glutton": "Cosmic Badgers",
    "Drunk Cats": "Polar Yetis",
    "Year of Jarvis": "Rocket Pandas",
}
SAMPLE_MY_TEAM = "Quantum Ferrets"

BANNER = (
    '<div class="degraded" style="border-left-color:#3d5a73"><b>Sanitized sample.</b> '
    "Team names are fictional; NFL players and projections are real, from a live data "
    "pull on {date}. League identifiers and the real decision log are not published. "
    "Generated by scripts/make_sample_report.py.</div>"
)

ILLUSTRATIVE_NOTE = (
    '<p class="note"><b>Illustrative only:</b> the transactions in this section are '
    "invented for this sample report so the section renders; the real league's decision "
    "log is deliberately not published.</p>"
)


RENDERER_SOURCES = ("fantasy_sim/weekly_report.py", "fantasy_sim/positional_tiers.py")


def renderer_fingerprint(repo):
    """sha256 over the report renderer's sources. The published sample embeds this
    stamp and a docs guard pins it, so a renderer change without a regenerated sample
    fails at pre-commit -- the published sample cannot silently lag the code
    (2026-09-04). Scope is the HTML renderer + shared table CSS/JS, deliberately:
    chart-producing modules live in the engine, and fingerprinting those would demand
    a sample refresh on every MAJOR whether or not the report changed."""
    import hashlib
    h = hashlib.sha256()
    for rel in RENDERER_SOURCES:
        with open(os.path.join(repo, rel), "rb") as f:
            h.update(f.read())
    return h.hexdigest()


def leak_check(html, forbidden):
    """Every forbidden string must be absent from the artifact. Returns the hits."""
    return sorted({f for f in forbidden if f and f in html})


def illustrative_log_rows(week, now_iso):
    """Fictional decision-log rows in the real schema (real NFL player names, fictional
    teams), so the sample shows what the section looks like."""
    def player(name, mean):
        return {"name": name, "player_id": "0", "projection": {"mean": mean}}
    return [
        {"transaction_id": "sample-1", "week": week, "created": now_iso, "type": "waiver",
         "teams": [SAMPLE_MY_TEAM], "is_mine": True, "faab_bid": 9,
         "snapshot_is_retroactive": False, "snapshot_lag_days": 0.1,
         "adds": [player("Tyjae Spears", 8.6)], "drops": [player("Roschon Johnson", 5.1)]},
        {"transaction_id": "sample-2", "week": week, "created": now_iso, "type": "free_agent",
         "teams": ["Cosmic Badgers"], "is_mine": False, "faab_bid": None,
         "snapshot_is_retroactive": False, "snapshot_lag_days": 0.3,
         "adds": [player("Tommy Tremble", 4.9)], "drops": []},
        {"record_type": "evaluation", "transaction_id": "sample-1", "evaluated_at": now_iso,
         "n_sims": 3000, "batches": 10, "post_execution_reversed": False,
         "teams": {SAMPLE_MY_TEAM: {"champ_pct": {"delta": 0.4, "se": 0.6},
                                    "playoff_pct": {"delta": 0.9, "se": 1.1}}}},
    ]


def main(argv=None):
    repo = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    sys.path.insert(0, repo)
    from fantasy_sim import config

    # Captured BEFORE mutation: everything the artifact must not contain.
    forbidden = (list(config.TEAM_NAME_MAP.keys()) + list(config.TEAM_NAME_MAP.values())
                 + [config.MY_TEAM, config.LEAGUE_ID, str(config.ESPN_LEAGUE_ID)])

    # In-place mutation propagates to every module that imported these objects.
    for user, real in list(config.TEAM_NAME_MAP.items()):
        config.TEAM_NAME_MAP[user] = FICTIONAL[real]
    profiles = dict(config.MANAGER_PROFILES)
    config.MANAGER_PROFILES.clear()
    config.MANAGER_PROFILES.update({FICTIONAL[k]: v for k, v in profiles.items()})
    config.MY_TEAM = SAMPLE_MY_TEAM   # sync's is_mine flag imports this lazily

    scratch = tempfile.mkdtemp(prefix="sample_report_")
    cwd = os.getcwd()
    try:
        os.makedirs(os.path.join(scratch, "data", "logs"))
        os.makedirs(os.path.join(scratch, "data", "current"))
        # Seed the EMA prior: absent players with zero live projections (NA/PUP) survive
        # only by carrying the previous sync's baseline mean -- without a prior the engine's
        # pre-flight abort fires (it did, on the first generation attempt). The baselines
        # file carries player names and NFL teams only; no league identity to leak.
        shutil.copy(os.path.join(repo, "data", "current", "player_baselines.json"),
                    os.path.join(scratch, "data", "current", "player_baselines.json"))
        now_iso = _dt.datetime.now(_dt.timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")
        with open(os.path.join(scratch, "data", "logs", "decision_log.jsonl"), "w",
                  encoding="utf-8") as f:
            for row in illustrative_log_rows(1, now_iso):
                f.write(json.dumps(row) + "\n")

        os.chdir(scratch)
        from scripts.weekly_report import main as report_main
        report_main(["--full", "--embed", "--team", SAMPLE_MY_TEAM])

        archive = os.path.join(scratch, "data", "decisions", "week_01", "archive")
        embeds = sorted(f for f in os.listdir(archive)
                        if f.endswith("_embed.html") and "FAILED" not in f)
        if not embeds:
            raise SystemExit("the sanitized run FAILED -- no publishable report was produced; "
                             "see the FAILED digest in " + archive)
        html = open(os.path.join(archive, embeds[-1]), encoding="utf-8").read()
    finally:
        os.chdir(cwd)

    # Post-fixes: banner under the h1; tier-table links neutralized (they point into
    # data/weeks/, which does not exist on Pages); illustrative note under the log h2.
    html = html.replace("</h1>", "</h1>" + BANNER.format(date=now_iso[:10]), 1)
    html = re.sub(r'<p class="note">Full ranked tables:.*?</p>',
                  '<p class="note">Full ranked tables are not included in this sample.</p>',
                  html, count=1)
    if '<h2 id="decision-log">' in html:
        html = re.sub(r'(<h2 id="decision-log">.*?</h2>)', r"\1" + ILLUSTRATIVE_NOTE,
                      html, count=1)

    html += f"\n<!-- renderer-fingerprint: {renderer_fingerprint(repo)} -->\n"

    hits = leak_check(html, forbidden)
    if hits:
        raise SystemExit(f"LEAK CHECK FAILED -- refusing to publish; found: {hits}")

    out = os.path.join(repo, "docs", "sample", "weekly_report_sample.html")
    os.makedirs(os.path.dirname(out), exist_ok=True)
    with open(out, "w", encoding="utf-8", newline="") as f:
        f.write(html)
    shutil.rmtree(scratch, ignore_errors=True)
    print(f"leak check clean ({len(forbidden)} forbidden strings, 0 hits)")
    print(f"sample -> {out}  ({os.path.getsize(out) // (1024 * 1024)} MB)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
